# Generated by Django 2.2 on 2019-04-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='full',
            field=models.BooleanField(default=False),
        ),
    ]
