# Generated by Django 2.2 on 2019-04-23 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profile_word'),
        ('core', '0003_profile_color'),
    ]

    operations = [
    ]
