# Generated by Django 2.2 on 2019-04-23 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20190423_1049'),
        ('core', '0004_merge_20190423_1055'),
    ]

    operations = [
    ]
