# Generated by Django 2.2 on 2019-04-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190423_1348'),
        ('core', '0006_auto_20190424_1412'),
    ]

    operations = [
    ]
