# Generated by Django 2.2 on 2019-04-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_profile_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='host',
            field=models.BooleanField(default=False),
        ),
    ]
