# Generated by Django 2.2 on 2019-04-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20190425_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='JSON',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
