# Generated by Django 2.2 on 2019-04-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_merge_20190425_1250'),
        ('core', '0013_auto_20190426_1809'),
    ]

    operations = [
    ]
