# Generated by Django 2.2 on 2019-04-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge_20190427_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rounds',
            field=models.IntegerField(default=1),
        ),
    ]
